apiVersion: v1
kind: ConfigMap
metadata:
  name: coworker-config
data:
  DB_NAME: coworkerDB
  DB_USERNAME: dbuser
  DB_HOST: postgresql-service
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQxMjM=