apiVersion: v1
kind: ConfigMap
metadata:
  name: coworker
data:
  DB_NAME: coworkerDB
  DB_USER: dbuser
  DB_HOST: 10.100.230.29
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQxMjM=